1st test & connector
shukal94/aircompany_repo pull request #10
Opened 2019-02-08 16:34 UTC by dbulka

Planes connector with methods
Plane test

2019-02-11 08:38 UTC, shukal94 requested changes
good, but comments

2019-02-11 08:38 UTC, shukal94 commented on aircompany.ini
> +[config]
do not commit this file)

2019-02-11 08:38 UTC, shukal94 commented on core/controllers/flight/flights_controller.py
> +    def select(self):
def read(self) is much more better

2019-02-11 08:38 UTC, shukal94 commented on utils/context.py
> +CONFIG_FILE_PATH = 'C:\\Users\\bulka\\aircompany_repo\\aircompany.ini'
for future commits please remove your own absolute path

2019-02-11 08:38 UTC, shukal94 commented on utils/sandbox.py
> +    print('{}'.format(args))
do not include your test modules into commits

2019-02-14 17:19 UTC, zipziprar approved these changes

2019-02-14 17:24 UTC, Litsvin approved these changes

2019-02-14 17:25 UTC, shukal94 approved these changes

2019-02-14 17:25 UTC, merged