'classes'
shukal94/aircompany_repo pull request #3
Opened 2019-02-01 21:55 UTC by dbulka

2019-02-01 23:16 UTC, shukal94 requested changes
please, read pep-8 and basic methods definition

2019-02-01 23:16 UTC, shukal94 commented on controller/order.py
> +    def calc_flight_settings(self, *args,  **kwargs)
blank line at EOF please

2019-02-01 23:16 UTC, shukal94 commented on controller/order.py
> +    def calc_ticket(self, *args,  **kwargs)
add : and description
def do(*args, **kwargs):
   """ lllalala """

2019-02-01 23:16 UTC, shukal94 commented on flight_settings/business.py
> +class BusinessFlight(Flight)
it's uniterpretable code, fix it, and dont forget about line at EOF

2019-02-01 23:16 UTC, shukal94 commented on flight_settings/common.py
> +class CommonFlight(Flight)
same

2019-02-01 23:16 UTC, shukal94 commented on flight_settings/flight.py
> +    def choose_luggage(self, *args, **kwargs)
the same as previvous

2019-02-01 23:16 UTC, shukal94 commented on model/admin.py
> +    def make_changes(self, *args, **kwargs)
see above

2019-02-01 23:16 UTC, shukal94 commented on model/customer.py
> +    def buy_ticket(self):
add `pass` or docstring into methods body

2019-02-01 23:16 UTC, shukal94 commented on model/guest.py
> +        self.id = id
blank line at EOF

2019-02-01 23:16 UTC, shukal94 commented on model/user.py
> +    def order_ticket(self, *args, **kwargs)
see above

2019-02-01 23:16 UTC, shukal94 commented on ticket/child_ticket.py
> +class ChildTicket(Ticket)
see above

2019-02-01 23:16 UTC, shukal94 commented on ticket/full_ticket.py
> +class FullTicket(Ticket)
see above

2019-02-01 23:16 UTC, shukal94 commented on ticket/ticket.py
> +    def change_menu(self, *args, **kwargs)
see above

2019-02-03 11:44 UTC, shukal94 requested changes
good, but double check about blank lines at end of file

2019-02-03 11:45 UTC, shukal94 commented
and place these files accordingly to init struct

2019-02-04 20:23 UTC, shukal94 approved these changes
Good job

2019-02-04 20:58 UTC, zipziprar approved these changes

2019-02-04 20:58 UTC, merged